// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var Dom = require("@testing-library/dom");

function makeByTextOptions(selector, exact, ignore, normalizer, param) {
  return {
          selector: Js_undefined.fromOption(selector),
          exact: Js_undefined.fromOption(exact),
          ignore: Js_undefined.fromOption(ignore),
          normalizer: Js_undefined.fromOption(normalizer)
        };
}

function getByText(options, element, matcher) {
  return Dom.getByText(element, matcher.VAL, options);
}

function findByText(options, matcher, element) {
  return Dom.findByText(element, matcher.VAL, options);
}

exports.makeByTextOptions = makeByTextOptions;
exports.getByText = getByText;
exports.findByText = findByText;
/* @testing-library/dom Not a pure module */
