// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var Dom = require("@testing-library/dom");

function makeByDisplayValueOptions(exact, normalizer, param) {
  return {
          exact: Js_undefined.fromOption(exact),
          normalizer: Js_undefined.fromOption(normalizer)
        };
}

function getByDisplayValue(options, matcher, element) {
  return Dom.getByDisplayValue(element, matcher.VAL, options);
}

function findByDisplayValue(options, matcher, element) {
  return Dom.findByDisplayValue(element, matcher.VAL, options);
}

exports.makeByDisplayValueOptions = makeByDisplayValueOptions;
exports.getByDisplayValue = getByDisplayValue;
exports.findByDisplayValue = findByDisplayValue;
/* @testing-library/dom Not a pure module */
