// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var Dom = require("@testing-library/dom");

function makeByTestIdOptions(exact, normalizer, param) {
  return {
          exact: Js_undefined.fromOption(exact),
          normalizer: Js_undefined.fromOption(normalizer)
        };
}

function getByTestId(options, matcher, element) {
  return Dom.getByTestId(element, matcher.VAL, options);
}

function findByTestId(options, matcher, element) {
  return Dom.findByTestId(element, matcher.VAL, options);
}

exports.makeByTestIdOptions = makeByTestIdOptions;
exports.getByTestId = getByTestId;
exports.findByTestId = findByTestId;
/* @testing-library/dom Not a pure module */
