// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Dom = require("@testing-library/dom");

function getByRole(options, matcher, element) {
  return Dom.getByRole(element, matcher.VAL, options.VAL);
}

function findByRole(options, matcher, element) {
  return Dom.findByRole(element, matcher.VAL, options);
}

exports.getByRole = getByRole;
exports.findByRole = findByRole;
/* @testing-library/dom Not a pure module */
