// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function makeOptions(exact, selector, name, param) {
  return {
          NAME: "WithString",
          VAL: {
            name: Js_undefined.fromOption(name),
            selector: Js_undefined.fromOption(selector),
            exact: Js_undefined.fromOption(exact)
          }
        };
}

function makeOptionsWithRegex(exact, selector, name, param) {
  return {
          NAME: "WithRegExp",
          VAL: {
            name: Js_undefined.fromOption(name),
            selector: Js_undefined.fromOption(selector),
            exact: Js_undefined.fromOption(exact)
          }
        };
}

function makeOptionsWithFunction(exact, selector, name, param) {
  return {
          NAME: "WithFunction",
          VAL: {
            name: Js_undefined.fromOption(name),
            selector: Js_undefined.fromOption(selector),
            exact: Js_undefined.fromOption(exact)
          }
        };
}

exports.makeOptions = makeOptions;
exports.makeOptionsWithRegex = makeOptionsWithRegex;
exports.makeOptionsWithFunction = makeOptionsWithFunction;
/* No side effect */
