// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var Dom = require("@testing-library/dom");

function makeOptions(exact, selector, name, param) {
  return {
          NAME: "WithString",
          VAL: {
            name: Js_undefined.fromOption(name),
            selector: Js_undefined.fromOption(selector),
            exact: Js_undefined.fromOption(exact)
          }
        };
}

function makeOptionsWithRegex(exact, selector, name, param) {
  return {
          NAME: "WithRegExp",
          VAL: {
            name: Js_undefined.fromOption(name),
            selector: Js_undefined.fromOption(selector),
            exact: Js_undefined.fromOption(exact)
          }
        };
}

function makeOptionsWithFunction(exact, selector, name, param) {
  return {
          NAME: "WithFunction",
          VAL: {
            name: Js_undefined.fromOption(name),
            selector: Js_undefined.fromOption(selector),
            exact: Js_undefined.fromOption(exact)
          }
        };
}

function getByRole(options, matcher, element) {
  return Dom.getByRole(element, matcher.VAL, options.VAL);
}

function findByRole(options, matcher, element) {
  return Dom.findByRole(element, matcher.VAL, options);
}

function getAllByRole(options, matcher, element) {
  return Dom.getAllByRole(element, matcher.VAL, options);
}

function queryAllByRole(options, matcher, element) {
  return Dom.queryAllByRole(element, matcher.VAL, options);
}

function findAllByRole(options, matcher, element) {
  return Dom.findAllByRole(element, matcher.VAL, options);
}

exports.makeOptions = makeOptions;
exports.makeOptionsWithRegex = makeOptionsWithRegex;
exports.makeOptionsWithFunction = makeOptionsWithFunction;
exports.getByRole = getByRole;
exports.findByRole = findByRole;
exports.getAllByRole = getAllByRole;
exports.queryAllByRole = queryAllByRole;
exports.findAllByRole = findAllByRole;
/* @testing-library/dom Not a pure module */
