// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var Dom = require("@testing-library/dom");

function makeByTitleOptions(exact, normalizer, param) {
  return {
          exact: Js_undefined.fromOption(exact),
          normalizer: Js_undefined.fromOption(normalizer)
        };
}

function getByTitle(options, matcher, element) {
  return Dom.getByTitle(element, matcher.VAL, options);
}

function findByTitle(options, matcher, element) {
  return Dom.findByTitle(element, matcher.VAL, options);
}

exports.makeByTitleOptions = makeByTitleOptions;
exports.getByTitle = getByTitle;
exports.findByTitle = findByTitle;
/* @testing-library/dom Not a pure module */
