// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_undefined = require("rescript/lib/js/js_undefined.js");
var Dom = require("@testing-library/dom");

function makeByAltTextOptions(exact, normalizer, param) {
  return {
          exact: Js_undefined.fromOption(exact),
          normalizer: Js_undefined.fromOption(normalizer)
        };
}

function getByAltText(options, matcher, element) {
  return Dom.getByAltText(element, matcher.VAL, options);
}

function findByAltText(options, matcher, element) {
  return Dom.findByAltText(element, matcher.VAL, options);
}

function getAllByAltText(options, matcher, element) {
  return Dom.getAllByAltText(element, matcher.VAL, options);
}

function queryAllByAltText(options, matcher, element) {
  return Dom.queryAllByAltText(element, matcher.VAL, options);
}

function findAllByAltText(options, matcher, element) {
  return Dom.findAllByAltText(element, matcher.VAL, options);
}

exports.makeByAltTextOptions = makeByAltTextOptions;
exports.getByAltText = getByAltText;
exports.findByAltText = findByAltText;
exports.getAllByAltText = getAllByAltText;
exports.queryAllByAltText = queryAllByAltText;
exports.findAllByAltText = findAllByAltText;
/* @testing-library/dom Not a pure module */
