// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Dom = require("@testing-library/dom");
var DomTestingLibrary__Queries__ByRole = require("./DomTestingLibrary__Queries__ByRole.js");
var DomTestingLibrary__Queries__ByText = require("./DomTestingLibrary__Queries__ByText.js");
var DomTestingLibrary__Queries__ByTitle = require("./DomTestingLibrary__Queries__ByTitle.js");
var DomTestingLibrary__Queries__ByTestId = require("./DomTestingLibrary__Queries__ByTestId.js");
var DomTestingLibrary__Queries__ByAltText = require("./DomTestingLibrary__Queries__ByAltText.js");
var DomTestingLibrary__Queries__ByLabelText = require("./DomTestingLibrary__Queries__ByLabelText.js");
var DomTestingLibrary__Queries__ByDisplayValue = require("./DomTestingLibrary__Queries__ByDisplayValue.js");
var DomTestingLibrary__Queries__ByPlaceholderText = require("./DomTestingLibrary__Queries__ByPlaceholderText.js");

var screen = Dom.screen;

var makeByAltTextOptions = DomTestingLibrary__Queries__ByAltText.makeByAltTextOptions;

var getByAltText = DomTestingLibrary__Queries__ByAltText.getByAltText;

var findByAltText = DomTestingLibrary__Queries__ByAltText.findByAltText;

var makeByDisplayValueOptions = DomTestingLibrary__Queries__ByDisplayValue.makeByDisplayValueOptions;

var getByDisplayValue = DomTestingLibrary__Queries__ByDisplayValue.getByDisplayValue;

var findByDisplayValue = DomTestingLibrary__Queries__ByDisplayValue.findByDisplayValue;

var makeByLabelTextOptions = DomTestingLibrary__Queries__ByLabelText.makeByLabelTextOptions;

var getByLabelText = DomTestingLibrary__Queries__ByLabelText.getByLabelText;

var findByLabelText = DomTestingLibrary__Queries__ByLabelText.findByLabelText;

var makeByPlaceholderTextOptions = DomTestingLibrary__Queries__ByPlaceholderText.makeByPlaceholderTextOptions;

var getByPlaceholderText = DomTestingLibrary__Queries__ByPlaceholderText.getByPlaceholderText;

var findByPlaceholderText = DomTestingLibrary__Queries__ByPlaceholderText.findByPlaceholderText;

var makeOptions = DomTestingLibrary__Queries__ByRole.makeOptions;

var makeOptionsWithRegex = DomTestingLibrary__Queries__ByRole.makeOptionsWithRegex;

var makeOptionsWithFunction = DomTestingLibrary__Queries__ByRole.makeOptionsWithFunction;

var getByRole = DomTestingLibrary__Queries__ByRole.getByRole;

var findByRole = DomTestingLibrary__Queries__ByRole.findByRole;

var getAllByRole = DomTestingLibrary__Queries__ByRole.getAllByRole;

var queryAllByRole = DomTestingLibrary__Queries__ByRole.queryAllByRole;

var findAllByRole = DomTestingLibrary__Queries__ByRole.findAllByRole;

var makeByTestIdOptions = DomTestingLibrary__Queries__ByTestId.makeByTestIdOptions;

var getByTestId = DomTestingLibrary__Queries__ByTestId.getByTestId;

var findByTestId = DomTestingLibrary__Queries__ByTestId.findByTestId;

var makeByTextOptions = DomTestingLibrary__Queries__ByText.makeByTextOptions;

var getByText = DomTestingLibrary__Queries__ByText.getByText;

var findByText = DomTestingLibrary__Queries__ByText.findByText;

var getAllByText = DomTestingLibrary__Queries__ByText.getAllByText;

var queryAllByText = DomTestingLibrary__Queries__ByText.queryAllByText;

var findAllByText = DomTestingLibrary__Queries__ByText.findAllByText;

var makeByTitleOptions = DomTestingLibrary__Queries__ByTitle.makeByTitleOptions;

var getByTitle = DomTestingLibrary__Queries__ByTitle.getByTitle;

var findByTitle = DomTestingLibrary__Queries__ByTitle.findByTitle;

exports.makeByAltTextOptions = makeByAltTextOptions;
exports.getByAltText = getByAltText;
exports.findByAltText = findByAltText;
exports.makeByDisplayValueOptions = makeByDisplayValueOptions;
exports.getByDisplayValue = getByDisplayValue;
exports.findByDisplayValue = findByDisplayValue;
exports.makeByLabelTextOptions = makeByLabelTextOptions;
exports.getByLabelText = getByLabelText;
exports.findByLabelText = findByLabelText;
exports.makeByPlaceholderTextOptions = makeByPlaceholderTextOptions;
exports.getByPlaceholderText = getByPlaceholderText;
exports.findByPlaceholderText = findByPlaceholderText;
exports.makeOptions = makeOptions;
exports.makeOptionsWithRegex = makeOptionsWithRegex;
exports.makeOptionsWithFunction = makeOptionsWithFunction;
exports.getByRole = getByRole;
exports.findByRole = findByRole;
exports.getAllByRole = getAllByRole;
exports.queryAllByRole = queryAllByRole;
exports.findAllByRole = findAllByRole;
exports.makeByTestIdOptions = makeByTestIdOptions;
exports.getByTestId = getByTestId;
exports.findByTestId = findByTestId;
exports.makeByTextOptions = makeByTextOptions;
exports.getByText = getByText;
exports.findByText = findByText;
exports.getAllByText = getAllByText;
exports.queryAllByText = queryAllByText;
exports.findAllByText = findAllByText;
exports.makeByTitleOptions = makeByTitleOptions;
exports.getByTitle = getByTitle;
exports.findByTitle = findByTitle;
exports.screen = screen;
/* screen Not a pure module */
