// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_undefined = require("rescript/lib/js/js_undefined.js");
var Dom = require("@testing-library/dom");

function makeByLabelTextOptions(selector, exact, normalizer, param) {
  return {
          selector: Js_undefined.fromOption(selector),
          exact: Js_undefined.fromOption(exact),
          normalizer: Js_undefined.fromOption(normalizer)
        };
}

function getByLabelText(options, matcher, element) {
  return Dom.getByLabelText(element, matcher.VAL, options);
}

function findByLabelText(options, matcher, element) {
  return Dom.findByLabelText(element, matcher.VAL, options);
}

exports.makeByLabelTextOptions = makeByLabelTextOptions;
exports.getByLabelText = getByLabelText;
exports.findByLabelText = findByLabelText;
/* @testing-library/dom Not a pure module */
