// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var Dom = require("@testing-library/dom");

function makeByPlaceholderTextOptions(exact, normalizer, param) {
  return {
          exact: Js_undefined.fromOption(exact),
          normalizer: Js_undefined.fromOption(normalizer)
        };
}

function getByPlaceholderText(options, matcher, element) {
  return Dom.getByPlaceholderText(element, matcher.VAL, options);
}

function findByPlaceholderText(options, matcher, element) {
  return Dom.findByPlaceholderText(element, matcher.VAL, options);
}

exports.makeByPlaceholderTextOptions = makeByPlaceholderTextOptions;
exports.getByPlaceholderText = getByPlaceholderText;
exports.findByPlaceholderText = findByPlaceholderText;
/* @testing-library/dom Not a pure module */
