// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Dom = require("@testing-library/dom");
var DomTestingLibrary__Queries__ByRole = require("./DomTestingLibrary__Queries__ByRole.js");
var DomTestingLibrary__Queries__ByText = require("./DomTestingLibrary__Queries__ByText.js");
var DomTestingLibrary__Queries__ByTitle = require("./DomTestingLibrary__Queries__ByTitle.js");
var DomTestingLibrary__Queries__ByTestId = require("./DomTestingLibrary__Queries__ByTestId.js");
var DomTestingLibrary__Queries__ByAltText = require("./DomTestingLibrary__Queries__ByAltText.js");
var DomTestingLibrary__Queries__ByLabelText = require("./DomTestingLibrary__Queries__ByLabelText.js");
var DomTestingLibrary__Queries__ByDisplayValue = require("./DomTestingLibrary__Queries__ByDisplayValue.js");
var DomTestingLibrary__Queries__ByPlaceholderText = require("./DomTestingLibrary__Queries__ByPlaceholderText.js");

var screen = Dom.screen;

var makeByAltTextOptions = DomTestingLibrary__Queries__ByAltText.makeByAltTextOptions;

var getByAltText = DomTestingLibrary__Queries__ByAltText.getByAltText;

var findByAltText = DomTestingLibrary__Queries__ByAltText.findByAltText;

var getAllByAltText = DomTestingLibrary__Queries__ByAltText.getAllByAltText;

var queryAllByAltText = DomTestingLibrary__Queries__ByAltText.queryAllByAltText;

var findAllByAltText = DomTestingLibrary__Queries__ByAltText.findAllByAltText;

var makeByDisplayValueOptions = DomTestingLibrary__Queries__ByDisplayValue.makeByDisplayValueOptions;

var getByDisplayValue = DomTestingLibrary__Queries__ByDisplayValue.getByDisplayValue;

var findByDisplayValue = DomTestingLibrary__Queries__ByDisplayValue.findByDisplayValue;

var makeByLabelTextOptions = DomTestingLibrary__Queries__ByLabelText.makeByLabelTextOptions;

var getByLabelText = DomTestingLibrary__Queries__ByLabelText.getByLabelText;

var findByLabelText = DomTestingLibrary__Queries__ByLabelText.findByLabelText;

var makeByPlaceholderTextOptions = DomTestingLibrary__Queries__ByPlaceholderText.makeByPlaceholderTextOptions;

var getByPlaceholderText = DomTestingLibrary__Queries__ByPlaceholderText.getByPlaceholderText;

var findByPlaceholderText = DomTestingLibrary__Queries__ByPlaceholderText.findByPlaceholderText;

var makeByRoleOptions = DomTestingLibrary__Queries__ByRole.makeByRoleOptions;

var makeByRoleOptionsWithRegex = DomTestingLibrary__Queries__ByRole.makeByRoleOptionsWithRegex;

var makeByRoleOptionsWithFunction = DomTestingLibrary__Queries__ByRole.makeByRoleOptionsWithFunction;

var getByRole = DomTestingLibrary__Queries__ByRole.getByRole;

var findByRole = DomTestingLibrary__Queries__ByRole.findByRole;

var getAllByRole = DomTestingLibrary__Queries__ByRole.getAllByRole;

var queryAllByRole = DomTestingLibrary__Queries__ByRole.queryAllByRole;

var findAllByRole = DomTestingLibrary__Queries__ByRole.findAllByRole;

var makeByTestIdOptions = DomTestingLibrary__Queries__ByTestId.makeByTestIdOptions;

var getByTestId = DomTestingLibrary__Queries__ByTestId.getByTestId;

var findByTestId = DomTestingLibrary__Queries__ByTestId.findByTestId;

var getAllByTestId = DomTestingLibrary__Queries__ByTestId.getAllByTestId;

var queryAllByTestId = DomTestingLibrary__Queries__ByTestId.queryAllByTestId;

var findAllByTestId = DomTestingLibrary__Queries__ByTestId.findAllByTestId;

var makeByTextOptions = DomTestingLibrary__Queries__ByText.makeByTextOptions;

var getByText = DomTestingLibrary__Queries__ByText.getByText;

var findByText = DomTestingLibrary__Queries__ByText.findByText;

var getAllByText = DomTestingLibrary__Queries__ByText.getAllByText;

var queryAllByText = DomTestingLibrary__Queries__ByText.queryAllByText;

var findAllByText = DomTestingLibrary__Queries__ByText.findAllByText;

var makeByTitleOptions = DomTestingLibrary__Queries__ByTitle.makeByTitleOptions;

var getByTitle = DomTestingLibrary__Queries__ByTitle.getByTitle;

var findByTitle = DomTestingLibrary__Queries__ByTitle.findByTitle;

var getAllByTitle = DomTestingLibrary__Queries__ByTitle.getAllByTitle;

var queryAllByTitle = DomTestingLibrary__Queries__ByTitle.queryAllByTitle;

var findAllByTitle = DomTestingLibrary__Queries__ByTitle.findAllByTitle;

exports.makeByAltTextOptions = makeByAltTextOptions;
exports.getByAltText = getByAltText;
exports.findByAltText = findByAltText;
exports.getAllByAltText = getAllByAltText;
exports.queryAllByAltText = queryAllByAltText;
exports.findAllByAltText = findAllByAltText;
exports.makeByDisplayValueOptions = makeByDisplayValueOptions;
exports.getByDisplayValue = getByDisplayValue;
exports.findByDisplayValue = findByDisplayValue;
exports.makeByLabelTextOptions = makeByLabelTextOptions;
exports.getByLabelText = getByLabelText;
exports.findByLabelText = findByLabelText;
exports.makeByPlaceholderTextOptions = makeByPlaceholderTextOptions;
exports.getByPlaceholderText = getByPlaceholderText;
exports.findByPlaceholderText = findByPlaceholderText;
exports.makeByRoleOptions = makeByRoleOptions;
exports.makeByRoleOptionsWithRegex = makeByRoleOptionsWithRegex;
exports.makeByRoleOptionsWithFunction = makeByRoleOptionsWithFunction;
exports.getByRole = getByRole;
exports.findByRole = findByRole;
exports.getAllByRole = getAllByRole;
exports.queryAllByRole = queryAllByRole;
exports.findAllByRole = findAllByRole;
exports.makeByTestIdOptions = makeByTestIdOptions;
exports.getByTestId = getByTestId;
exports.findByTestId = findByTestId;
exports.getAllByTestId = getAllByTestId;
exports.queryAllByTestId = queryAllByTestId;
exports.findAllByTestId = findAllByTestId;
exports.makeByTextOptions = makeByTextOptions;
exports.getByText = getByText;
exports.findByText = findByText;
exports.getAllByText = getAllByText;
exports.queryAllByText = queryAllByText;
exports.findAllByText = findAllByText;
exports.makeByTitleOptions = makeByTitleOptions;
exports.getByTitle = getByTitle;
exports.findByTitle = findByTitle;
exports.getAllByTitle = getAllByTitle;
exports.queryAllByTitle = queryAllByTitle;
exports.findAllByTitle = findAllByTitle;
exports.screen = screen;
/* screen Not a pure module */
