// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Dom = require("@testing-library/dom");
var DomTestingLibrary__Queries__ByRole = require("./DomTestingLibrary__Queries__ByRole.js");
var DomTestingLibrary__Queries__ByText = require("./DomTestingLibrary__Queries__ByText.js");
var DomTestingLibrary__Queries__Options = require("./DomTestingLibrary__Queries__Options.js");
var DomTestingLibrary__Queries__ByLabelText = require("./DomTestingLibrary__Queries__ByLabelText.js");
var DomTestingLibrary__Queries__ByPlaceholderText = require("./DomTestingLibrary__Queries__ByPlaceholderText.js");

var screen = Dom.screen;

function getByDisplayValue(element, matcher) {
  return Dom.getByDisplayValue(element, matcher.VAL);
}

function getByAltText(element, matcher) {
  return Dom.getByAltText(element, matcher.VAL);
}

function getByTitle(element, matcher) {
  return Dom.getByTitle(element, matcher.VAL);
}

function getByTestId(element, matcher) {
  return Dom.getByTestId(element, matcher.VAL);
}

function findByDisplayValue(element, matcher) {
  return Dom.findByDisplayValue(element, matcher.VAL);
}

function findByAltText(element, matcher) {
  return Dom.findByAltText(element, matcher.VAL);
}

function findByTitle(element, matcher) {
  return Dom.findByTitle(element, matcher.VAL);
}

function findByTestId(element, matcher) {
  return Dom.findByTestId(element, matcher.VAL);
}

var makeByLabelTextOptions = DomTestingLibrary__Queries__ByLabelText.makeByLabelTextOptions;

var getByLabelText = DomTestingLibrary__Queries__ByLabelText.getByLabelText;

var findByLabelText = DomTestingLibrary__Queries__ByLabelText.findByLabelText;

var makeByPlaceholderTextOptions = DomTestingLibrary__Queries__ByPlaceholderText.makeByPlaceholderTextOptions;

var getByPlaceholderText = DomTestingLibrary__Queries__ByPlaceholderText.getByPlaceholderText;

var findByPlaceholderText = DomTestingLibrary__Queries__ByPlaceholderText.findByPlaceholderText;

var getByRole = DomTestingLibrary__Queries__ByRole.getByRole;

var findByRole = DomTestingLibrary__Queries__ByRole.findByRole;

var makeByTextOptions = DomTestingLibrary__Queries__ByText.makeByTextOptions;

var getByText = DomTestingLibrary__Queries__ByText.getByText;

var findByText = DomTestingLibrary__Queries__ByText.findByText;

var makeOptions = DomTestingLibrary__Queries__Options.makeOptions;

var makeOptionsWithRegex = DomTestingLibrary__Queries__Options.makeOptionsWithRegex;

var makeOptionsWithFunction = DomTestingLibrary__Queries__Options.makeOptionsWithFunction;

exports.makeByLabelTextOptions = makeByLabelTextOptions;
exports.getByLabelText = getByLabelText;
exports.findByLabelText = findByLabelText;
exports.makeByPlaceholderTextOptions = makeByPlaceholderTextOptions;
exports.getByPlaceholderText = getByPlaceholderText;
exports.findByPlaceholderText = findByPlaceholderText;
exports.getByRole = getByRole;
exports.findByRole = findByRole;
exports.makeByTextOptions = makeByTextOptions;
exports.getByText = getByText;
exports.findByText = findByText;
exports.makeOptions = makeOptions;
exports.makeOptionsWithRegex = makeOptionsWithRegex;
exports.makeOptionsWithFunction = makeOptionsWithFunction;
exports.screen = screen;
exports.getByDisplayValue = getByDisplayValue;
exports.getByAltText = getByAltText;
exports.getByTitle = getByTitle;
exports.getByTestId = getByTestId;
exports.findByDisplayValue = findByDisplayValue;
exports.findByAltText = findByAltText;
exports.findByTitle = findByTitle;
exports.findByTestId = findByTestId;
/* screen Not a pure module */
