// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var DomTestingLibrary__Queries = require("./DomTestinLibrary__Queries/DomTestingLibrary__Queries.js");

var screen = DomTestingLibrary__Queries.screen;

var getByRole = DomTestingLibrary__Queries.getByRole;

var getByText = DomTestingLibrary__Queries.getByText;

var getByLabelText = DomTestingLibrary__Queries.getByLabelText;

var getByPlaceholderText = DomTestingLibrary__Queries.getByPlaceholderText;

var getByDisplayValue = DomTestingLibrary__Queries.getByDisplayValue;

var getByAltText = DomTestingLibrary__Queries.getByAltText;

var getByTitle = DomTestingLibrary__Queries.getByTitle;

var getByTestId = DomTestingLibrary__Queries.getByTestId;

var findByRole = DomTestingLibrary__Queries.findByRole;

var findByText = DomTestingLibrary__Queries.findByText;

var findByLabelText = DomTestingLibrary__Queries.findByLabelText;

var findByPlaceholderText = DomTestingLibrary__Queries.findByPlaceholderText;

var findByDisplayValue = DomTestingLibrary__Queries.findByDisplayValue;

var findByAltText = DomTestingLibrary__Queries.findByAltText;

var findByTitle = DomTestingLibrary__Queries.findByTitle;

var findByTestId = DomTestingLibrary__Queries.findByTestId;

exports.screen = screen;
exports.getByRole = getByRole;
exports.getByText = getByText;
exports.getByLabelText = getByLabelText;
exports.getByPlaceholderText = getByPlaceholderText;
exports.getByDisplayValue = getByDisplayValue;
exports.getByAltText = getByAltText;
exports.getByTitle = getByTitle;
exports.getByTestId = getByTestId;
exports.findByRole = findByRole;
exports.findByText = findByText;
exports.findByLabelText = findByLabelText;
exports.findByPlaceholderText = findByPlaceholderText;
exports.findByDisplayValue = findByDisplayValue;
exports.findByAltText = findByAltText;
exports.findByTitle = findByTitle;
exports.findByTestId = findByTestId;
/* DomTestingLibrary__Queries Not a pure module */
