// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Dom = require("@testing-library/dom");
var DomTestingLibrary__Queries = require("./DomTestingLibrary__Queries/DomTestingLibrary__Queries.js");

function waitFor(prim) {
  return Dom.waitFor(prim);
}

var makeByAltTextOptions = DomTestingLibrary__Queries.makeByAltTextOptions;

var getByAltText = DomTestingLibrary__Queries.getByAltText;

var findByAltText = DomTestingLibrary__Queries.findByAltText;

var makeByDisplayValueOptions = DomTestingLibrary__Queries.makeByDisplayValueOptions;

var getByDisplayValue = DomTestingLibrary__Queries.getByDisplayValue;

var findByDisplayValue = DomTestingLibrary__Queries.findByDisplayValue;

var makeByLabelTextOptions = DomTestingLibrary__Queries.makeByLabelTextOptions;

var getByLabelText = DomTestingLibrary__Queries.getByLabelText;

var findByLabelText = DomTestingLibrary__Queries.findByLabelText;

var makeByPlaceholderTextOptions = DomTestingLibrary__Queries.makeByPlaceholderTextOptions;

var getByPlaceholderText = DomTestingLibrary__Queries.getByPlaceholderText;

var findByPlaceholderText = DomTestingLibrary__Queries.findByPlaceholderText;

var makeOptions = DomTestingLibrary__Queries.makeOptions;

var makeOptionsWithRegex = DomTestingLibrary__Queries.makeOptionsWithRegex;

var makeOptionsWithFunction = DomTestingLibrary__Queries.makeOptionsWithFunction;

var getByRole = DomTestingLibrary__Queries.getByRole;

var findByRole = DomTestingLibrary__Queries.findByRole;

var getAllByRole = DomTestingLibrary__Queries.getAllByRole;

var queryAllByRole = DomTestingLibrary__Queries.queryAllByRole;

var findAllByRole = DomTestingLibrary__Queries.findAllByRole;

var makeByTestIdOptions = DomTestingLibrary__Queries.makeByTestIdOptions;

var getByTestId = DomTestingLibrary__Queries.getByTestId;

var findByTestId = DomTestingLibrary__Queries.findByTestId;

var makeByTextOptions = DomTestingLibrary__Queries.makeByTextOptions;

var getByText = DomTestingLibrary__Queries.getByText;

var findByText = DomTestingLibrary__Queries.findByText;

var makeByTitleOptions = DomTestingLibrary__Queries.makeByTitleOptions;

var getByTitle = DomTestingLibrary__Queries.getByTitle;

var findByTitle = DomTestingLibrary__Queries.findByTitle;

var screen = DomTestingLibrary__Queries.screen;

exports.makeByAltTextOptions = makeByAltTextOptions;
exports.getByAltText = getByAltText;
exports.findByAltText = findByAltText;
exports.makeByDisplayValueOptions = makeByDisplayValueOptions;
exports.getByDisplayValue = getByDisplayValue;
exports.findByDisplayValue = findByDisplayValue;
exports.makeByLabelTextOptions = makeByLabelTextOptions;
exports.getByLabelText = getByLabelText;
exports.findByLabelText = findByLabelText;
exports.makeByPlaceholderTextOptions = makeByPlaceholderTextOptions;
exports.getByPlaceholderText = getByPlaceholderText;
exports.findByPlaceholderText = findByPlaceholderText;
exports.makeOptions = makeOptions;
exports.makeOptionsWithRegex = makeOptionsWithRegex;
exports.makeOptionsWithFunction = makeOptionsWithFunction;
exports.getByRole = getByRole;
exports.findByRole = findByRole;
exports.getAllByRole = getAllByRole;
exports.queryAllByRole = queryAllByRole;
exports.findAllByRole = findAllByRole;
exports.makeByTestIdOptions = makeByTestIdOptions;
exports.getByTestId = getByTestId;
exports.findByTestId = findByTestId;
exports.makeByTextOptions = makeByTextOptions;
exports.getByText = getByText;
exports.findByText = findByText;
exports.makeByTitleOptions = makeByTitleOptions;
exports.getByTitle = getByTitle;
exports.findByTitle = findByTitle;
exports.screen = screen;
exports.waitFor = waitFor;
/* @testing-library/dom Not a pure module */
