// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Dom = require("@testing-library/dom");
var DomTestingLibrary__Queries = require("./DomTestingLibrary__Queries/DomTestingLibrary__Queries.js");

function waitFor(prim) {
  return Dom.waitFor(prim);
}

var makeByTextOptions = DomTestingLibrary__Queries.makeByTextOptions;

var getByText = DomTestingLibrary__Queries.getByText;

var findByText = DomTestingLibrary__Queries.findByText;

var getByRole = DomTestingLibrary__Queries.getByRole;

var findByRole = DomTestingLibrary__Queries.findByRole;

var makeOptions = DomTestingLibrary__Queries.makeOptions;

var makeOptionsWithRegex = DomTestingLibrary__Queries.makeOptionsWithRegex;

var makeOptionsWithFunction = DomTestingLibrary__Queries.makeOptionsWithFunction;

var makeByLabelTextOptions = DomTestingLibrary__Queries.makeByLabelTextOptions;

var getByLabelText = DomTestingLibrary__Queries.getByLabelText;

var findByLabelText = DomTestingLibrary__Queries.findByLabelText;

var screen = DomTestingLibrary__Queries.screen;

var getByPlaceholderText = DomTestingLibrary__Queries.getByPlaceholderText;

var getByDisplayValue = DomTestingLibrary__Queries.getByDisplayValue;

var getByAltText = DomTestingLibrary__Queries.getByAltText;

var getByTitle = DomTestingLibrary__Queries.getByTitle;

var getByTestId = DomTestingLibrary__Queries.getByTestId;

var findByPlaceholderText = DomTestingLibrary__Queries.findByPlaceholderText;

var findByDisplayValue = DomTestingLibrary__Queries.findByDisplayValue;

var findByAltText = DomTestingLibrary__Queries.findByAltText;

var findByTitle = DomTestingLibrary__Queries.findByTitle;

var findByTestId = DomTestingLibrary__Queries.findByTestId;

exports.makeByTextOptions = makeByTextOptions;
exports.getByText = getByText;
exports.findByText = findByText;
exports.getByRole = getByRole;
exports.findByRole = findByRole;
exports.makeOptions = makeOptions;
exports.makeOptionsWithRegex = makeOptionsWithRegex;
exports.makeOptionsWithFunction = makeOptionsWithFunction;
exports.makeByLabelTextOptions = makeByLabelTextOptions;
exports.getByLabelText = getByLabelText;
exports.findByLabelText = findByLabelText;
exports.screen = screen;
exports.getByPlaceholderText = getByPlaceholderText;
exports.getByDisplayValue = getByDisplayValue;
exports.getByAltText = getByAltText;
exports.getByTitle = getByTitle;
exports.getByTestId = getByTestId;
exports.findByPlaceholderText = findByPlaceholderText;
exports.findByDisplayValue = findByDisplayValue;
exports.findByAltText = findByAltText;
exports.findByTitle = findByTitle;
exports.findByTestId = findByTestId;
exports.waitFor = waitFor;
/* @testing-library/dom Not a pure module */
