// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_undefined = require("rescript/lib/js/js_undefined.js");
var UserEvent = require("@testing-library/user-event").default;

function click(options, init, element) {
  var options$1 = Js_undefined.fromOption(options);
  var init$1 = Js_undefined.fromOption(init);
  UserEvent.click(element, options$1, init$1);
  
}

function type_(options, element, text) {
  var options$1 = Js_undefined.fromOption(options);
  UserEvent.type(element, text, options$1);
  
}

function keyboard(options, text) {
  var options$1 = Js_undefined.fromOption(options);
  UserEvent.keyboard(text, options$1);
  
}

exports.click = click;
exports.type_ = type_;
exports.keyboard = keyboard;
/* @testing-library/user-event Not a pure module */
