include DomTestingLibrary__Queries__ByAltText
include DomTestingLibrary__Queries__ByDisplayValue
include DomTestingLibrary__Queries__ByLabelText
include DomTestingLibrary__Queries__ByPlaceholderText
include DomTestingLibrary__Queries__ByRole
include DomTestingLibrary__Queries__ByTestId
include DomTestingLibrary__Queries__ByText
include DomTestingLibrary__Queries__ByTitle
include DomTestingLibrary__Queries__Options

@module("@testing-library/dom")
external screen: 'document = "screen"
let screen = screen
